[package]
name = "rossmann_forecast"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.46", features = ["lazy", "csv", "temporal", "dtype-date", "strings", "round_series", "trigonometry"] }
chrono = "0.4"
anyhow = "1.0"
ndarray = "0.15"
linfa = "0.7"
linfa-linear = "0.7"
burn = { version = "0.16", features = ["ndarray", "wgpu", "autodiff", "train"] }
smartcore = "0.3.2"
